In [2]:
import numpy as np
import numpy.ma as ma

In [8]:
x =np.array([1,2,4,5,7])
print(x)

[1 2 4 5 7]


In [17]:
mx = ma.masked_array(x,mask = [0,0,1,0,0])

In [18]:
print(mx)

[1 2 -- 5 7]


In [19]:
mx.mean()

3.75

In [22]:
y = ma.array([1,2,3,4,5,6],mask = [0,0,1,0,0,0])

In [21]:
y = ma.array([1, 2, 3], mask = [0, 1, 0])

In [25]:
z = ma.masked_array([1,20,4,5,60,40,50,4,50],4)

In [26]:
print(z)

[-- -- -- -- -- -- -- -- --]


In [29]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [32]:
mdata = ma.masked_array(data,masked = [True,True,True,False,True,False])
print(mdata)

[0 1 2 3 4 5]


In [33]:
mdata.mean()

2.5

In [34]:
mdata

masked_array(data=[0, 1, 2, 3, 4, 5],
             mask=False,
       fill_value=999999)

In [36]:
c = np.linspace(0,10,50)
c

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [37]:
print(c.shape)

(50,)


In [43]:
m = np.array([[np.arange(10)]])
m.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [47]:
k = m.ravel(order = 'C')

In [51]:
k.shape
k

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
j = m.ravel(order = 'F')

In [54]:
j.shape
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
v= k.reshape(-1,5)
v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
v.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [67]:
x = np.array([np.arange(10)])
y = np.array([np.arange(10,20,1)])
print(x.shape)
print(y.shape)

(1, 10)
(1, 10)


In [69]:
np.stack((x,y))

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [70]:
np.stack((x,y),axis = -1)

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 16],
        [ 7, 17],
        [ 8, 18],
        [ 9, 19]]])

In [71]:
np.vstack((x,y))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [73]:
import cv2 as cv
import numpy as np


In [74]:
image2 = cv.imread("C:/Users/VEDIT/Desktop/mike/cat-example.jpg")


In [80]:
def rotate(img,angle,rotpoint = None):
    (height,width) = img.shape[:2]
    if(rotpoint == None):
        rotpoint = (width//2,height//2)
    rotMat = cv.getRotationMatrix2D(rotpoint,angle,1.0)
    dimensions = (width,height)
    
    return cv.warpAffine(image,rotMat,dimensions)


In [81]:
rotated  = rotate(image2,45)
cv.imshow('rotated',rotated)
cv.waitKey(0)

NameError: name 'image' is not defined