In [6]:
from sklearn.compose import make_column_transformer

In [7]:
from sklearn.preprocessing import OneHotEncoder

In [107]:
one = OneHotEncoder(sparse = True)

In [108]:
x = [['small','mediam','large']]

In [109]:
one.fit(x)

OneHotEncoder()

In [112]:
one.categories_

[array(['small'], dtype=object),
 array(['mediam'], dtype=object),
 array(['large'], dtype=object)]

In [102]:
x = one.transform(x)

In [104]:
print(x)

  (0, 0)	1.0
  (0, 1)	1.0
  (0, 2)	1.0


In [105]:
one.get_params()

{'categories': 'auto',
 'drop': None,
 'dtype': numpy.float64,
 'handle_unknown': 'error',
 'sparse': True}

In [113]:
# only for encoding target variables

from sklearn.preprocessing import LabelEncoder

In [125]:
# must be dimensional 
y = ['one','two','three']

In [126]:
enc = LabelEncoder()

In [127]:
encoded = enc.fit_transform(y)

In [129]:
enc.classes_

array(['one', 'three', 'two'], dtype='<U5')

In [128]:
encoded

array([0, 2, 1], dtype=int64)

In [131]:
from sklearn.preprocessing import OneHotEncoder

In [177]:
one = OneHotEncoder(drop = 'first')

In [178]:
import numpy as np

In [179]:
x = ['small','mediam','large']
x = np.array(x,dtype = '<U6')
x.dtype

dtype('<U6')

In [159]:
encoded = one.fit_transform(x.reshape((-1,1)))

In [162]:
# strange isn't it
print(encoded)

  (0, 2)	1.0
  (1, 1)	1.0
  (2, 0)	1.0


In [163]:
# make sure to convert to array
encoded.toarray()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [164]:
x = np.arange(100)

In [166]:
from sklearn.preprocessing import LabelBinarizer

In [168]:
from sklearn.preprocessing import OrdinalEncoder

In [172]:
c = np.array(['small','mediam','large']).reshape((-1,1))

In [173]:
ordenc = OrdinalEncoder()

In [175]:
o = ordenc.fit_transform(c)

In [176]:
o

array([[2.],
       [1.],
       [0.]])