In [1]:
import tensorflow as tf
import os
import numpy as np
import cProfile

In [2]:
tf.executing_eagerly()

True

In [3]:
x = [[4.]]
m = tf.matmul(x,x)
print("hello",m.numpy())

hello [[16.]]


In [4]:
print("hello, {}".format(m))

hello, [[16.]]


In [22]:
a = tf.constant([[1,2,3,4],[1,2,3,4]])
b = tf.constant([[2,3,4,5],[2,3,4,5]])
C = tf.constant([[1,2],[1,2],[1,2],[1,2]])

In [23]:
print(tf.add(a,b).numpy())

[[3 5 7 9]
 [3 5 7 9]]


In [24]:
c = tf.Variable([2,3,4,5],dtype = tf.float32)
print(c.numpy())

[2. 3. 4. 5.]


In [25]:
print(tf.multiply(a,b).numpy())


[[ 2  6 12 20]
 [ 2  6 12 20]]


In [26]:
print(tf.matmul(a,C).numpy())

[[10 20]
 [10 20]]


In [41]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1,max_num):
        num = tf.constant(num)
    
        if (num%3==0 and num %5 ==0):
            print("fizzbuzz")
        elif(num %3 == 0):
            print("fizz")
        elif (num%5 == 0):
            print("buzz")
            counter+=1
        
        else:
            print(num.numpy())
fizzbuzz(30)       

1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29


## auto differentiation

In [54]:
w = tf.Variable([[3.0]])
with tf.GradientTape() as tape:
    loss = w*w
    grad = tape.gradient(loss,w)
    print(grad.numpy())
    

[[6.]]


In [70]:
(mnist_images, mnist_labels), _ = tf.keras.datasets.mnist.load_data()
dataset = tf.data.Dataset.from_tensor_slices(
  (tf.cast(mnist_images[...,tf.newaxis]/255, tf.float32),
   tf.cast(mnist_labels,tf.int64)))
dataset = dataset.shuffle(1000).batch(32)
mnist_model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(16,[3,3],activation = 'relu',input_shape = (None,None,1)),
    tf.keras.layers.Conv2D(16,[3,3],activation = 'relu'),
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(10)
    ])

In [71]:
for images,labels in dataset.take(1):
    print("Logits: ", mnist_model(images[0:1]).numpy())

Logits:  [[ 0.02450528 -0.01287182 -0.05914166  0.04487088 -0.01710892  0.00990111
  -0.00833228 -0.01761301 -0.03273392  0.00288826]]


In [82]:
# optimizer = tf.keras.optimizers.Adam()
# loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)
# loss_history = []

In [84]:
optimizer = tf.keras.optimizers.Adam()
loss_object = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

#loss_history = []

In [81]:
# def train_step(images,labels):
#     with GradientTape as tape:
#         logits = mnist_model(images,trainning = True)
#         # Add asserts to check the shape of the output.
#         tf.debugging.assert_equals(logits.shape,(32,10))
#         loss_value = loss_object(labels, logits)

#         loss_history.append(loss_value.numpy().mean())
#         grads = gradient(loss_value,mnist_model.trainable_variables)
#         optimizer.apply_gradients(zip(gradients,mnist_model.trainable_variables))
        

In [79]:
def train(epochs):
    for epoch in range(epochs):
         for (batch, (images, labels)) in enumerate(dataset):
                train_step(images, labels)
                print ('Epoch {} finished'.format(epoch))